services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - react
      - angular
      - vue
      - flask
      - django

  react:
    build: ./react-app
    expose:
      - "3000"

  angular:
    build: ./angular-app
    expose:
      - "4200"

  vue:
    build: ./vue-app
    expose:
      - "5173"

  flask:
    build: ./flask-app
    expose:
      - "5000"

  django:
    build: ./django-app
    expose:
      - "8000"