[build]
  publish = "deploy/static"
  command = "./deploy-static.sh"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/react/*"
  to = "/react/index.html"
  status = 200

[[redirects]]
  from = "/vue/*"
  to = "/vue/index.html"
  status = 200

[[redirects]]
  from = "/angular/*"
  to = "/angular/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/shared/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"