name: Deploy Static Portfolio

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install React dependencies
      working-directory: ./react-app
      run: yarn install

    - name: Build React app
      working-directory: ./react-app
      run: yarn build

    - name: Install Vue dependencies
      working-directory: ./vue-app
      run: yarn install

    - name: Build Vue app
      working-directory: ./vue-app
      run: yarn build

    - name: Prepare deployment
      run: |
        mkdir -p deploy/static
        cp -r react-app/dist deploy/static/react
        cp -r vue-app/dist deploy/static/vue
        cp -r angular-app/dist deploy/static/angular
        cp -r nginx/launcher/* deploy/static/
        cp -r shared deploy/static/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy/static
        publish_branch: gh-pages