name: Deploy Static Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install React dependencies
      working-directory: ./react-app
      run: yarn install --frozen-lockfile

    - name: Build React app
      working-directory: ./react-app
      run: yarn build

    - name: Install Vue dependencies
      working-directory: ./vue-app
      run: yarn install --frozen-lockfile

    - name: Build Vue app
      working-directory: ./vue-app
      run: yarn build

    - name: Prepare deployment
      run: |
        mkdir -p deploy/static
        cp -r react-app/dist deploy/static/react
        cp -r vue-app/dist deploy/static/vue
        cp -r angular-app/dist deploy/static/angular
        cp -r nginx/launcher/* deploy/static/
        cp -r shared deploy/static/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy/static